=== TomKrauss/trend-workshop/xml.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
       targetNamespace="http://www.gebit.de" elementFormDefault="qualified" xmlns="http://www.gebit.de">
  <xsd:simpleType name="de.gebit.trend.workshop.bo.ProductCategoryEnum" id="ProductCategoryEnum">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  <xsd:simpleType name="int" id="int">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  <xsd:simpleType name="java.sql.Date" id="sqlDate">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  <xsd:complexType name="de.gebit.trend.bo.persistence.keygen.HighestKey">
    <xsd:sequence>
      <xsd:element name="className" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="memberName" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="number" type="xsd:long" nillable="false" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="de.gebit.trend.workshop.bo.Basket">
    <xsd:sequence>
      <xsd:element name="_customer_id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="created" type="java.sql.Date" nillable="true" minOccurs="0"/>
      <xsd:element name="id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="lastUser" type="xsd:string" nillable="true" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="de.gebit.trend.workshop.bo.BasketPosition">
    <xsd:sequence>
      <xsd:element name="_basket_id" type="xsd:long" nillable="true" minOccurs="0"/>
      <xsd:element name="_product_id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="lastUser" type="xsd:string" nillable="true" minOccurs="0"/>
      <xsd:element name="quantity" type="int" nillable="true" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="de.gebit.trend.workshop.bo.Customer">
    <xsd:sequence>
      <xsd:element name="city" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="firstname" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="lastUser" type="xsd:string" nillable="true" minOccurs="0"/>
      <xsd:element name="lastname" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="street" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="zipCode" type="xsd:string" nillable="false" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="de.gebit.trend.workshop.bo.Product">
    <xsd:sequence>
      <xsd:element name="description" type="xsd:string" nillable="true" minOccurs="0"/>
      <xsd:element name="id" type="xsd:long" nillable="false" minOccurs="1"/>
      <xsd:element name="lastUser" type="xsd:string" nillable="true" minOccurs="0"/>
      <xsd:element name="name" type="xsd:string" nillable="false" minOccurs="1"/>
      <xsd:element name="price" type="xsd:decimal" nillable="false" minOccurs="1"/>
      <xsd:element name="productCategory" type="de.gebit.trend.workshop.bo.ProductCategoryEnum" nillable="false" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="TRENDBusinessObjects">
   <xsd:complexType>
    <xsd:sequence>
    <xsd:element name="de.gebit.trend.bo.persistence.keygen.HighestKey" type="de.gebit.trend.bo.persistence.keygen.HighestKey"  minOccurs="0" maxOccurs="unbounded">
    <xsd:key name="k1">
     <xsd:selector xpath="./de.gebit.trend.bo.persistence.keygen.HighestKey"/>
     <xsd:field xpath="className"/>
     <xsd:field xpath="memberName"/>
    </xsd:key>
    </xsd:element>
    <xsd:element name="de.gebit.trend.workshop.bo.Basket" type="de.gebit.trend.workshop.bo.Basket"  minOccurs="0" maxOccurs="unbounded">
    <xsd:key name="k2">
     <xsd:selector xpath="./de.gebit.trend.workshop.bo.Basket"/>
     <xsd:field xpath="id"/>
    </xsd:key>
    </xsd:element>
    <xsd:element name="de.gebit.trend.workshop.bo.BasketPosition" type="de.gebit.trend.workshop.bo.BasketPosition"  minOccurs="0" maxOccurs="unbounded">
    <xsd:key name="k3">
     <xsd:selector xpath="./de.gebit.trend.workshop.bo.BasketPosition"/>
     <xsd:field xpath="id"/>
    </xsd:key>
    </xsd:element>
    <xsd:element name="de.gebit.trend.workshop.bo.Customer" type="de.gebit.trend.workshop.bo.Customer"  minOccurs="0" maxOccurs="unbounded">
    <xsd:key name="k4">
     <xsd:selector xpath="./de.gebit.trend.workshop.bo.Customer"/>
     <xsd:field xpath="id"/>
    </xsd:key>
    </xsd:element>
    <xsd:element name="de.gebit.trend.workshop.bo.Product" type="de.gebit.trend.workshop.bo.Product"  minOccurs="0" maxOccurs="unbounded">
    <xsd:key name="k5">
     <xsd:selector xpath="./de.gebit.trend.workshop.bo.Product"/>
     <xsd:field xpath="id"/>
    </xsd:key>
    </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string"/>
   </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== TomKrauss/trend-workshop/xml.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<TRENDBusinessObjects version="6.5"
xmlns="http://www.gebit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.gebit.de xml.xsd">
<de.gebit.trend.bo.persistence.keygen.HighestKey>
    <className>default</className>
    <memberName>default</memberName>
    <number>3</number>
</de.gebit.trend.bo.persistence.keygen.HighestKey>
<de.gebit.trend.workshop.bo.Basket>
    <_customer_id>12884901888</_customer_id>
    <created>2022-01-19</created>
    <id>8589934593</id>
    <lastUser>Tom</lastUser>
</de.gebit.trend.workshop.bo.Basket>
<de.gebit.trend.workshop.bo.BasketPosition>
    <_basket_id>8589934593</_basket_id>
    <_product_id>4294967298</_product_id>
    <id>8589934592</id>
    <quantity>1</quantity>
</de.gebit.trend.workshop.bo.BasketPosition>
<de.gebit.trend.workshop.bo.Customer>
    <city>Berlin</city>
    <firstname>Tom</firstname>
    <id>12884901888</id>
    <lastUser>Tom</lastUser>
    <lastname>Krauﬂ</lastname>
    <street>Schwiebusser Straﬂe</street>
    <zipCode>10965</zipCode>
</de.gebit.trend.workshop.bo.Customer>
<de.gebit.trend.workshop.bo.Product>
    <description>Cool phone, just released</description>
    <id>4294967296</id>
    <lastUser>Tom</lastUser>
    <name>I Phone</name>
    <price>1200.00</price>
    <productCategory>ELECTRONICS</productCategory>
</de.gebit.trend.workshop.bo.Product>
<de.gebit.trend.workshop.bo.Product>
    <description>Chiquita from Bolivia</description>
    <id>4294967297</id>
    <name>Bananas</name>
    <price>1.99</price>
    <productCategory>FOOD</productCategory>
</de.gebit.trend.workshop.bo.Product>
<de.gebit.trend.workshop.bo.Product>
    <description>Coll book by Tolkien</description>
    <id>4294967298</id>
    <name>Lord of the rings</name>
    <price>9.99</price>
    <productCategory>BOOKS</productCategory>
</de.gebit.trend.workshop.bo.Product>
</TRENDBusinessObjects>
